[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "googletrans>=4.0.2",
    "python-dotenv>=1.0.1",
    "python-telegram-bot==13.7",
    "telegram>=0.0.1",
]
